
logging:
  level:
    org.springframework.core.env: debug
    org.springframework.jndi: debug
    root: info
server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,text/html
    min-response-size: 2048
spring:
  jackson:
    serialization:
     write-dates-as-timestamps: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
initializr:
  boot-versions:
    - name: 1.5.10
      id: 1.5.10.RELEASE
      default: true
    - name: 1.5.11(SNAPSHOT)
      id: 1.5.11.BUILD-SNAPSHOT
      default: false
    - name: 2.0.0
      id: 2.0.0.RELEASE
      default: false
    - name: 2.0.1(SNAPSHOT)
      id: 2.0.1.BUILD-SNAPSHOT
      default: false
  group-id:
    value: io.hsweb
    description: hsweb's  own spring initializr project
  description:
    value: https://github.com/hs-web
  package-name:
    value: io.hsweb
  env:
    boms:
      azure:
        groupId: com.microsoft.azure
        artifactId: azure-spring-boot-bom
        versionProperty: azure.version
        mappings:
          - versionRange: "[1.5.4.RELEASE,2.0.0.M1)"
            version: 0.2.0
      spring-cloud:
        groupId: org.springframework.cloud
        artifactId: spring-cloud-dependencies
        versionProperty: spring-cloud.version
        order: 50
        mappings:
          - versionRange: "[1.2.3.RELEASE,1.3.0.RELEASE)"
            version: Angel.SR6
          - versionRange: "[1.3.0.RELEASE,1.4.0.RELEASE)"
            version: Brixton.SR7
          - versionRange: "[1.4.0.RELEASE,1.4.x.RELEASE]"
            version: Camden.SR7
          - versionRange: "[1.5.0.RELEASE,1.5.x.RELEASE]"
            version: Dalston.SR4
          - versionRange: "[1.5.x.BUILD-SNAPSHOT,2.0.0.M1)"
            version: Edgware.M1
            repositories: spring-milestones
          - versionRange: "[2.0.0.M2, 2.0.0.BUILD-SNAPSHOT)"
            version: Finchley.M2
            repositories: spring-milestones
          - versionRange: "2.0.0.BUILD-SNAPSHOT"
            version: Finchley.BUILD-SNAPSHOT
            repositories: spring-snapshots,spring-milestones
      spring-cloud-services:
        groupId: io.pivotal.spring.cloud
        artifactId: spring-cloud-services-dependencies
        versionProperty: spring-cloud-services.version
        additionalBoms: [spring-cloud]
        mappings:
          - versionRange: "[1.3.0.RELEASE,1.4.0.RELEASE)"
            version: 1.2.1.RELEASE
          - versionRange: "[1.4.0.RELEASE,1.5.x.RELEASE]"
            version: 1.5.0.RELEASE
          - versionRange: "[1.5.x.BUILD-SNAPSHOT, 2.0.0.M1)"
            version: 1.5.1.BUILD-SNAPSHOT
            repositories: spring-snapshots,spring-milestones
      spring-cloud-task:
        groupId: org.springframework.cloud
        artifactId: spring-cloud-task-dependencies
        versionProperty: spring-cloud-task.version
        order: 30
        mappings:
          - versionRange: "[1.3.0.RELEASE, 1.4.0.RELEASE]"
            version: 1.0.3.RELEASE
          - versionRange: "[1.4.0.RELEASE, 1.5.0.RC1)"
            version: 1.1.2.RELEASE
          - versionRange: "[1.5.0.RC1, 2.0.0.M1)"
            version: 1.2.2.RELEASE
          - versionRange: "[2.0.0.M2, 2.0.0.BUILD-SNAPSHOT)"
            version: 2.0.0.M1
            repositories: spring-milestones
          - versionRange: "2.0.0.BUILD-SNAPSHOT"
            version: 2.0.0.BUILD-SNAPSHOT
            repositories: spring-snapshots,spring-milestones
      vaadin:
        groupId: com.vaadin
        artifactId: vaadin-bom
        versionProperty: vaadin.version
        mappings:
          - versionRange: "[1.3.0.RELEASE, 1.5.0.M1)"
            version: 7.7.7
          - versionRange: "1.5.0.M1"
            version: 8.1.0
      keycloak:
        groupId: org.keycloak.bom
        artifactId: keycloak-adapter-bom
        versionProperty: keycloak.version
        version: 3.2.1.Final
    gradle:
      dependency-management-plugin-version: 0.6.0.RELEASE
    kotlin:
      version: 1.1.51
    repositories:
      nexus:
        name: Team Nexus Repository
        url: http://nexus.hsweb.me/content/groups/public/
        snapshots-enabled: true
  dependencies:
#  添加自己的依赖,按照模板依次复制即可
    - name: Framework #分组名称
      content:
        - name: 权限管理 #显示名称
          groupId: org.hswebframework.web
          artifactId: hsweb-system-authorization-starter
          repository: nexus #使用私服 私服在上面配置

        - name: 权限控制
          groupId: org.hswebframework.web
          artifactId: hsweb-authorization-basic
          repository: nexus

        - name: jwt
          groupId: org.hswebframework.web
          artifactId: hsweb-authorization-jwt
          repository: nexus

        - name: 组织架构
          groupId: org.hswebframework.web
          artifactId: hsweb-system-organizational-starter
          repository: nexus

        - name: 动态表单
          groupId: org.hswebframework.web
          artifactId: hsweb-system-dynamic-form-starter
          repository: nexus

        - name: 模板管理
          groupId: org.hswebframework.web
          artifactId: hsweb-system-template-starter
          repository: nexus

        - name: 自定义模块
          groupId: org.hswebframework.web
          artifactId: hsweb-system-module-starter
          repository: nexus

        - name: 定时调度
          groupId: org.hswebframework.web
          artifactId: hsweb-system-schedule-starter
          repository: nexus

        - name: 动态脚本
          groupId: org.hswebframework.web
          artifactId: hsweb-system-script-starter
          repository: nexus

        - name: 访问日志
          groupId: org.hswebframework.web
          artifactId: hsweb-access-logging-aop
          repository: nexus

        - name: oauth2 server支持
          groupId: org.hswebframework.web
          artifactId: hsweb-system-oauth2-server-starter
          repository: nexus

        - name: oauth2 client支持
          groupId: org.hswebframework.web
          artifactId: hsweb-system-oauth2-client-starter
          repository: nexus

        - name: ueditor支持，需要引入文件上传功能
          groupId: org.hswebframework.web
          artifactId: hsweb-thirdparty-ueditor
          repository: nexus

        - name: 文件上传
          groupId: org.hswebframework.web
          artifactId: hsweb-system-file-starter
          repository: nexus

        - name: 数据库管理
          groupId: org.hswebframework.web
          artifactId: hsweb-system-database-manager-starter
          repository: nexus

        - name: 数据源
          groupId: org.hswebframework.web
          artifactId: hsweb-datasource-api
          repository: nexus




  types:
    - name: Maven Project
      id: maven-project
      description: Generate a Maven based project archive
      sts-id: starter.zip
      tags:
        build: maven
        format: project
      default: true
      action: /starter.zip
    - name: Maven POM
      id: maven-build
      description: Generate a Maven pom.xml
      sts-id: pom.xml
      tags:
        build: maven
        format: build
      default: false
      action: /pom.xml
    - name: Gradle Project
      id: gradle-project
      description: Generate a Gradle based project archive
      sts-id: gradle.zip
      tags:
        build: gradle
        format: project
      default: false
      action: /starter.zip
    - name: Gradle Config
      id: gradle-build
      description: Generate a Gradle build file
      sts-id: build.gradle
      tags:
        build: gradle
        format: build
      default: false
      action: /build.gradle
  packagings:
    - name: Jar
      id: jar
      default: true
    - name: War
      id: war
      default: false
  javaVersions:
    - id: 1.8
      default: true
    - id: 1.7
      default: false
    - id: 1.6
      default: false
  languages:
    - name: Java
      id: java
      default: true
    - name: Kotlin
      id: kotlin
      default: false
    - name: Groovy
      id: groovy
      default: false
  bootVersions:
    - name : Latest SNAPSHOT
      id: 1.2.4.BUILD-SNAPSHOT
      default: false
    - name: 1.2.3
      id: 1.2.3.RELEASE
      default: true
    - name: 1.1.12
      id: 1.1.12.RELEASE
      default: false

security:
    user:
      name: admin
      password: changdaye
